language: ruby
cache: bundler
before_script: createdb attr_pouch
sudo: false
script: DATABASE_URL="postgres:///attr_pouch" bundle exec rspec
addons:
  postgresql: "9.4"
env:
rvm:
  - 2.4.1
notifications:
  email: false
